# Generated by Django 3.1.4 on 2020-12-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=30)),
                ('github', models.CharField(max_length=60)),
                ('linkedin', models.CharField(max_length=60)),
                ('personal_website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('tags', models.ManyToManyField(to='post.Tag')),
                ('team', models.ManyToManyField(to='post.Author')),
            ],
        ),
    ]
