# Generated by Django 3.1.4 on 2020-12-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='facebook_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='whatsapp_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
