# Generated by Django 3.1.4 on 2021-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210102_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='feedback_amazed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='feedback_funny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='feedback_loved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='feedback_upvote',
            field=models.IntegerField(default=0),
        ),
    ]
