# Generated by Django 3.1.4 on 2021-01-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_blogpost_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIPLocator',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
