# Generated by Django 3.1.4 on 2021-01-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_emailiplocator'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailiplocator',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailiplocator',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
