# Generated by Django 3.1.4 on 2021-01-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210124_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(null=True, to='post.BlogPostComment'),
        ),
    ]
