# Generated by Django 3.1.4 on 2021-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_blogpost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='permission_granted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='post.BlogPostComment'),
        ),
    ]
